### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SaadatKhan** [naufalso/keras_nerf#4]
No matter which train file I run, I get this error: 

Traceback (most recent call last):
  File "C:\Users\YU_GMU\keras_nerf\train.py", line 166, in <module>
    main()
  File "C:\Users\YU_GMU\keras_nerf\train.py", line 151, in main
    nerf.fit(
  File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\tensorflow\python\eager\execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'GatherV2_1' defined at (most recent call last):
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\threading.py", line 937, in _bootstrap
      self._bootstrap_inner()
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\threading.py", line 980, in _bootstrap_inner
      self.run()
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\tensorflow\python\distribute\mirrored_run.py", line 386, in run
      self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\keras\engine\training.py", line 1135, in run_step
      outputs = model.train_step(data)
    File "C:\Users\YU_GMU\keras_nerf\keras_nerf\model\nerf\nerf.py", line 395, in train_step
      fine_chunk_results = self._predict_and_render_chunk(
    File "C:\Users\YU_GMU\keras_nerf\keras_nerf\model\nerf\nerf.py", line 186, in _predict_and_render_chunk
      fine_points_chunk = self.nerf_utils.fine_hierarchical_sampling_chunk(
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 150, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\tensorflow\python\eager\def_function.py", line 915, in __call__
      result = self._call(*args, **kwds)
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\tensorflow\python\eager\def_function.py", line 963, in _call
      self._initialize(args, kwds, add_initializers_to=initializers)
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\tensorflow\python\eager\def_function.py", line 785, in _initialize
      self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\tensorflow\python\eager\function.py", line 2523, in _get_concrete_function_internal_garbage_collected
      graph_function, _ = self._maybe_define_function(args, kwargs)
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\tensorflow\python\eager\function.py", line 2760, in _maybe_define_function
      graph_function = self._create_graph_function(args, kwargs)
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\tensorflow\python\eager\function.py", line 2670, in _create_graph_function
      func_graph_module.func_graph_from_py_func(
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\tensorflow\python\framework\func_graph.py", line 1247, in func_graph_from_py_func
      func_outputs = python_func(*func_args, **func_kwargs)
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\tensorflow\python\eager\def_function.py", line 677, in wrapped_fn
      out = weak_wrapped_fn().__wrapped__(*args, **kwds)
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\tensorflow\python\eager\function.py", line 3317, in bound_method_wrapper
      return wrapped_fn(*args, **kwargs)
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\tensorflow\python\framework\func_graph.py", line 1222, in autograph_handler
      return autograph.converted_call(
    File "C:\Users\YU_GMU\keras_nerf\keras_nerf\model\nerf\utils.py", line 87, in fine_hierarchical_sampling_chunk
      mid_points = tf.gather(mid_points, indicesG, axis=-1,
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 150, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\tensorflow\python\util\dispatch.py", line 1176, in op_dispatch_handler
      return dispatch_target(*args, **kwargs)
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\tensorflow\python\ops\array_ops.py", line 5297, in gather_v2
      return gather(
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 150, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\tensorflow\python\util\dispatch.py", line 1176, in op_dispatch_handler
      return dispatch_target(*args, **kwargs)
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\tensorflow\python\util\deprecation.py", line 561, in new_func
      return func(*args, **kwargs)
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\tensorflow\python\ops\array_ops.py", line 5279, in gather
      return gen_array_ops.gather_v2(
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 3956, in gather_v2
      _, _, _op, _outputs = _op_def_library._apply_op_helper(
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 797, in _apply_op_helper
      op = g._create_op_internal(op_type_name, inputs, dtypes=None,
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\tensorflow\python\framework\func_graph.py", line 735, in _create_op_internal
      return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\tensorflow\python\framework\ops.py", line 3800, in _create_op_internal
      ret = Operation(
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\tensorflow\python\framework\ops.py", line 2108, in __init__
      c_op = _create_c_op(g, node_def, inputs, control_input_ops, op_def=op_def)
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 150, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\tensorflow\python\framework\ops.py", line 1974, in _create_c_op
      tf_stack.extract_stack_for_op(c_op, stacklevel=3)
    File "C:\Users\YU_GMU\.conda\envs\keras_nerf\lib\site-packages\tensorflow\python\util\tf_stack.py", line 180, in extract_stack_for_op
      _tf_stack.extract_stack_for_op(
Node: 'GatherV2_1'
indices[722,74,1] = 63 is not in [0, 63)
         [[{{node GatherV2_1}}]] [Op:__inference_train_function_29279]

Could you give a work around?

**Comment by naufalso** [comment]
Which TensorFlow version do you use?
I checked it works well with the latest TF version.

**Comment by SaadatKhan** [comment]
Hi! Thanks for the reply
These are the packages and their corresponding versions I am using. I installed them from the requirements.txt file and these came up

Package                      Version
---------------------------- ---------
absl-py                      1.4.0
astunparse                   1.6.3
cachetools                   5.3.0
certifi                      2022.12.7
charset-normalizer           3.0.1
colorama                     0.4.6
contourpy                    1.0.7
cycler                       0.11.0
flatbuffers                  23.1.21
fonttools                    4.38.0
gast                         0.4.0
google-auth                  2.16.0
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
grpcio                       1.51.1
h5py                         3.8.0
idna                         3.4
imageio                      2.25.0
imageio-ffmpeg               0.4.8
importlib-metadata           6.0.0
keras                        2.11.0
kiwisolver                   1.4.4
libclang                     15.0.6.1
Markdown                     3.4.1
MarkupSafe                   2.1.2
matplotlib                   3.6.3
numpy                        1.24.1
oauthlib                     3.2.2
opt-einsum                   3.3.0
packaging                    23.0
Pillow                       9.4.0
pip                          22.3.1
protobuf                     3.19.6
pyasn1                       0.4.8
pyasn1-modules               0.2.8
pyparsing                    3.0.9
python-dateutil              2.8.2
requests                     2.28.2
requests-oauthlib            1.3.1
rsa                          4.9
setuptools                   65.6.3
six                          1.16.0
tensorboard                  2.11.2
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.11.0
tensorflow-estimator         2.11.0
tensorflow-intel             2.11.0
tensorflow-io-gcs-filesystem 0.30.0
termcolor                    2.2.0
tqdm                         4.64.1
typing_extensions            4.4.0
urllib3                      1.26.14
Werkzeug                     2.2.2
wheel                        0.37.1
wincertstore                 0.2
wrapt                        1.14.1
zipp                         3.12.0


I am also using an RTX 3090Ti in windows 10

**Comment by SaadatKhan** [comment]
It is basically a graph execution error (`tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'GatherV2_1' defined at (most recent call last):`)

I am stuck at this for quite some time.

**Comment by steezera** [comment]
Hi,I have the same problem, do you solve it? And how?

**Comment by wyu54** [comment]
If you open utils.py, around line 81, add tf.print(cdf.shape, mid_points.shape), you will find that the last dimension of the shape is 65 and 63, separately. Clearly, cdf is padded but mid_points is not. 

Therefore, my suggestion is: 
to change
        indices = tf.searchsorted(cdf, u, side="right") #Note: 1-64
        # define the boundaries
        below = tf.maximum(0, indices-1)
        above = tf.minimum(cdf.shape[-1]-1, indices) 
into 
        indices = tf.searchsorted(cdf, u, side="right")
        # define the boundaries
        below = tf.maximum(0, indices-2)
        above = tf.minimum(mid_points.shape[-1]-1, indices-1) # Why -1? 

Note that midpoints have shape 63 (0-62) while cdf has shape 65 (0-64). so mid_points[0] should correspond to cdf[1]. So there is a -1.
